
<h2 align="center">LIQUIDACION DE REMUNERACIONES</h2>

<p></p>
<p></p>
<p></p>

<div>

    <table border="1" cellpadding="4">
        <tr border="0">
            <td border="0"><strong>MES: <?php echo strtoupper($data['body'][0]->getPeriodoDescripcion()) ?></strong></td>
            <td border="0" align="right"><strong>FECHA EMISION: <?php echo date('d/m/Y') ?></strong></td>
        </tr>
        <tr valign="top">
            <td style="width: 25%; padding-left: 10px;">
                <table>
                    <tr>
                        <td>
                            <strong><?php echo $data['body'][0]->getEmpresaNombre() ?></strong>
                        </td>
                    </tr>
                    <tr>
                        <td>RUT: &nbsp;&nbsp;&nbsp;<?php echo $data['body'][0]->getEmpresaRut() ?></td>
                    </tr>
                    <tr>
                        <td><?php echo $data['body'][0]->getEmpresaDireccion() ?></td>
                    </tr>
                    <tr>
                        <td><?php echo $data['body'][0]->getEmpresaCiudad() ?></td>
                    </tr>
                </table>
            </td>
            <td style="border-left: solid 1px #a9a9a9; width: 75%;">
                <table>
                    <tr>
                        <th colspan="1">NOMBRE: </th>
                        <th colspan="3"><strong><?php echo $data['body'][0]->getTrabajadorNombre() ?></strong></th>
                        <th colspan="1">NUMERO: </th>
                        <th colspan="1"><strong><?php echo $data['body'][0]->getTrabajadorCodigo() ?></strong></th>
                    </tr>
                    <tr>
                        <td colspan="1">RUT: </td>
                        <td colspan="3"><strong><?php echo $data['body'][0]->getTrabajadorRut() ?></strong></td>
                        <td colspan="1">C.COSTO</td>
                        <td colspan="1"><strong><?php echo $data['body'][0]->getConCostoCodigo() ?></strong></td>
                    </tr>
                    <tr>
                        <td colspan="1">CARGO: </td>
                        <td colspan="3"><strong><?php echo $data['body'][0]->getCargo() ?></strong></td>
                        <td colspan="1">F. INGRESO: </td>
                        <td colspan="1"><strong><?php echo $data['body'][0]->getTrabajadorFechaIngreso() ?></strong></td>
                    </tr>
                    <tr>
                        <td colspan="1">AFP: </td>
                        <td colspan="5"><strong><?php echo $data['body'][0]->getAfp() ?></strong></td>
                    </tr>
                    <tr>
                        <td colspan="1">SALUD: </td>
                        <td colspan="5"><strong><?php echo $data['body'][0]->getIsapre() ?></strong></td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
    <br>
    <table border="1" cellpadding="4">
        <tr style="height: 20px;" valign="top">
            <td style="border-bottom: solid 1px #a9a9a9; text-align: center; width: 50%;">
                <strong>HABERES</strong>
            </td>
            <td style="border-left: solid 1px #a9a9a9; border-bottom: solid 1px #a9a9a9; width: 50%;">
            </td>
        </tr>
        <tr valign="top">
            <td style="width: 50%; padding-left: 10px;">
                <table style="width: 100%;">
                    <?php foreach ($data['haberes'] as $dat): ?>
                        <tr>
                            <td colspan="7"><?php echo $dat->getLiquidacionVariableDescripcion() ?></td>
                            <td align="right">          <?php echo $dat->getValor() ?></td>
                            <td></td>
                        </tr>
                    <?php endforeach; ?>
                </table>
            </td>
            <td style="border-left: solid 1px #a9a9a9; padding-left: 10px;">
                <table style="height: 100%; width: 100%;">
                    <?php foreach ($data['debito'] as $dat): ?>
                        <tr style="height: 20px;">
                            <td colspan="7"><?php echo $dat->getLiquidacionVariableDescripcion() ?></td>
                            <td align="right">     <?php echo $dat->getValor() ?></td>
                            <td></td>
                        </tr>
                    <?php endforeach; ?>
                    <tr>
                        <td style="vertical-align:bottom;"></td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr style="height: 20px;" valign="top">
            <td style="width: 50%;">
                <strong></strong>
            </td>
            <td style="padding-left: px; border-left: solid 1px #a9a9a9; border-top: solid 1px #a9a9a9;">
                <table style="width: 100%;">
                    <tr>
                        <td colspan="7"><strong>LIQUIDO A PAGAR ($)</strong></td>
                        <td align="right"><strong>   <?php echo $data['body'][0]->getLiquido() ?></strong></td>
                        <td></td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>

    <br><br>
    
    <p>Certifico que he recibido de <span style="font-weight: lighter"><?php echo $data['body'][0]->getEmpresaNombre() ?></span> a mi entera satisfaccion el saldo liquido indicado en la presente
        liquidacion y no tengo cargo ni cobro alguno de hacer por ninguno de los conceptos comprendidos.</p>
    <p>Deposito efectuado en el <?php echo $data['body'][0]->getBanco() ?></p>
    <br>
    <p></p>
    <p></p>
    <p></p>
    <p>FIRMA DEL TRABAJADOR: ______________________________ </p>
</div>