<div class="page-header">
    <h1>
        Liquidaciones
        <small>
            <i class="ace-icon fa fa-angle-double-right"></i>
            Mis Liquidaciones
        </small>
    </h1>
</div>

<div class="row">
    <div class="col-xs-12">
        <!-- PAGE CONTENT BEGINS -->
        <div class="row">
            <div class="col-xs-12">
                <ul>
                    <?php foreach ($liquidaciones as $liq): ?>
                    <li>
                        <a href="<?php echo $this->url('application/default', array('controller' => 'liquidaciones', 'action' => 'generar-pdf'), array('query' => array('per' => $liq->getPeri_codigo()))); ?>">
                            <?php echo $months[substr($liq->getPeri_codigo(), 4, 2)]; ?> - <?php echo substr($liq->getPeri_codigo(), 0, 4) ?>
                        </a>
                    </li>
                    <?php endforeach; ?>
                </ul>
            </div><!-- /.span -->
        </div><!-- /.row -->
    </div><!-- /.col -->
</div>