<h3>Usuarios</h3>

<?php foreach ($this->messages as $msg): ?>
    <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <strong>Oye!</strong> <?php echo $msg['msg']; ?>
    </div>
<?php endforeach; ?>

<hr>
<a class="btn btn-primary" href="<?php echo $this->url('devadmin/default', array('controller' => 'users', 'action' => 'add')); ?>">
    <span class="glyphicon glyphicon-plus-sign"></span>
    Agregar
</a>
<hr>


<table class="table table-condensed">
    <thead>
        <tr class="warning">
            <th>Username</th>
            <th>Roles</th>
            <th>Acción</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($users as $user): ?>
            <tr>
                <td><?php echo $user->getUsername(); ?></td>
                <td><?php echo $user->getRolesListString(); ?></td>
                <td>
                    <a href="<?php echo $this->url('devadmin/default', array('controller' => 'users', 'action' => 'edit'), array('query' => array('id' => $user->getIdUser()))); ?>">Editar</a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

