<h1 style="text-decoration: underline;" align="center">
    <span><?php echo $data->getP_titulo(); ?></span>
</h1>

<p></p>
<p></p>

<p style="text-align:justify;"><?php echo $data->getP_texto1(); ?></p>
<p style="text-align:justify;"><?php echo $data->getP_texto2(); ?></p>
<p style="text-align:justify;"><?php echo $data->getP_texto3(); ?></p>
<p style="text-align:justify;"><?php echo $data->getP_texto4(); ?></p>
<p style="text-align:justify;"><?php echo $data->getP_texto5(); ?></p>
<p style="text-align:justify;"><?php echo $data->getP_texto6(); ?></p>
<p style="text-align:justify;"><?php echo $data->getP_texto7(); ?></p>
<p style="text-align:justify;"><?php echo $data->getP_texto8(); ?></p>
<p style="text-align:justify;"><?php echo $data->getP_texto9(); ?></p>
<p style="text-align:justify;"><?php echo $data->getP_texto10(); ?></p>
<p style="text-align:justify;"><?php echo $data->getP_texto11(); ?></p>
<p style="text-align:justify;"><?php echo $data->getP_texto12(); ?></p>
<p style="text-align:justify;"><?php echo $data->getP_texto13(); ?></p>
<p style="text-align:justify;"><?php echo $data->getP_texto14(); ?></p>

<p></p>
<p></p>

<p>
    <?php if ($firma == 1): ?>
        <img align="center" src="<?php echo $this->basePath('/image/Firma.gif'); ?>" alt="test alt attribute" width="200" height="100" border="0" />
        <br>
    <?php endif; ?>
    <span><?php echo $data->getP_firma1(); ?></span><br>
    <span align="center"><?php echo $data->getP_firma2(); ?></span><br>
    <span align="center"><?php echo $data->getP_firma3(); ?></span><br>
</p>