<?php echo $this->doctype(); ?>
<html>
    <head>
        <title>Identificaci&oacute;n</title>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8">
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> 
        <link rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/bootstrap.min.css" />
        <link rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/font-awesome.min.css" />
        <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400,300" />
        <link rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/ace.nomodified.min.css" class="ace-main-stylesheet" id="main-ace-style" />
        <script src="<?php echo $this->basePath(); ?>/js/thirdparty/ace-extra.min.js"></script>
        <script src="<?php echo $this->basePath(); ?>/js/thirdparty/jquery.min.js"></script>
        <script src="<?php echo $this->basePath(); ?>/js/thirdparty/bootstrap.min.js"></script>
        <script src="<?php echo $this->basePath(); ?>/js/thirdparty/jquery-ui.custom.min.js"></script>
        <script src="<?php echo $this->basePath(); ?>/js/thirdparty/ace-elements.min.js"></script>
        <script src="<?php echo $this->basePath(); ?>/js/thirdparty/ace.min.js"></script>
        <script src="<?php echo $this->basePath(); ?>/js/thirdparty/notify.min.js"></script>
    </head>
    <body class="login-layout light-login">

        <?php if (isset($messages)): ?>
            <?php if (!empty($messages)): ?>
                <div id="alert-messages" style="display: none">
                    <?php foreach ($messages as $m): ?>
                        <div data-message="<?php echo $m['message']; ?>" data-classname="<?php echo $m['className']; ?>"></div>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>
        <?php endif; ?>

        <div class="main-container">
            <div class="main-content">
                <div class="row">
                    <div class="col-sm-10 col-sm-offset-1">
                        <?php echo $this->content; ?>
                    </div>
                </div>
            </div>
        </div>

        <script>

            $(document).ready(function () {

                if ($("#alert-messages").length) {

                    $("#alert-messages > div").each(function (index) {

                        var className = $(this).data('classname');
                        var message = $(this).data('message');

                        $.notify(message, {
                            className: className,
                            globalPosition: 'bottom center',
                            style: 'bootstrap',
                        });
                    });
                }
            });

        </script>
    </body>

</body>
</html>
