<div class="page-header">
    <h1>
        Solicitudes
        <small>
            <i class="ace-icon fa fa-angle-double-right"></i>
            Mis Solicitudes
        </small>
    </h1>
</div>

<div class="col-sm-12">

    <div class="tabbable">
        <ul class="nav nav-tabs" id="myTab">
            <li class="active">
                <a data-toggle="tab" href="#home" aria-expanded="true">
                    <i class="green ace-icon fa fa-home bigger-120"></i>
                    Mis Solicitudes
                </a>
            </li>
        </ul>
        <div class="tab-content">
            <div id="home" class="tab-pane fade active in">
                <table class="table table-condensed table-hover table-solicitudes">
                    <tbody>
                        <?php foreach ($solicitudes as $s): ?>
                            <tr>
                                <td>
                                    <?php if ($s->getTipo()->getCodigo() == \Application\Model\Entity\Solicitud::TIPO_VACACIONES): ?>
                                        <div class="icon-32-vacation"></div>
                                    <?php endif; ?>
                                    <?php if ($s->getTipo()->getCodigo() == \Application\Model\Entity\Solicitud::TIPO_ANTICIPO): ?>
                                        <div class="icon-32-money"></div>
                                    <?php endif; ?>
                                </td>
                                <td>
                                    <?php if ($s->getTipo()->getCodigo() == \Application\Model\Entity\Solicitud::TIPO_VACACIONES): ?>
                                        <a href="<?php echo $this->url('application/default', array('controller' => 'vacaciones', 'action' => 'detalle'), array('query' => array('id' => $s->getIdSolicitud(), 'tipo' => $s->getTipo()->getCodigo()))); ?>"><?php echo $s->getFechaIngreso(); ?></a>
                                    <?php endif; ?>
                                    <?php if ($s->getTipo()->getCodigo() == \Application\Model\Entity\Solicitud::TIPO_ANTICIPO): ?>
                                        <a href="<?php echo $this->url('application/default', array('controller' => 'anticipos', 'action' => 'detalle'), array('query' => array('id' => $s->getIdSolicitud(), 'tipo' => $s->getTipo()->getCodigo()))); ?>"><?php echo $s->getFechaIngreso(); ?></a>
                                    <?php endif; ?>
                                </td>
                                <td>
                                    <?php if ($s->getEstado()->getCod() == 'PENDIENTE'): ?>
                                        <span class="label label-warning arrowed arrowed-right"><?php echo $s->getEstado()->getDescripcion(); ?></span>
                                    <?php elseif ($s->getEstado()->getCod() == 'ACEPTADO'): ?>
                                        <span class="label label-success arrowed-in arrowed-in-right"><?php echo $s->getEstado()->getDescripcion(); ?></span>
                                    <?php elseif ($s->getEstado()->getCod() == 'RECHAZADO'): ?>
                                        <span class="label label-danger arrowed-in arrowed-in-right"><?php echo $s->getEstado()->getDescripcion(); ?></span>
                                    <?php elseif ($s->getEstado()->getCod() == 'ANULADO'): ?>
                                        <span class="label label-inverse arrowed arrowed-in-right"><?php echo $s->getEstado()->getCod(); ?></span>
                                    <?php endif; ?>
                                </td>
                                <td><?php echo $s->getObservaciones(); ?></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

