<div class="page-header">
    <h1>
        Formulario
        <small>
            <i class="ace-icon fa fa-angle-double-right"></i>
            Cambio de Clave
        </small>
    </h1>
</div>

<div class="row">
    <form class="form-horizontal" role="form" method="POST">

        <div class="form-group <?php echo $this->formElementErrors($form->get('password')) ? 'has-error' : ''; ?>">
            <?php echo $this->formLabel($form->get('password')); ?>
            <div class="col-xs-12 col-sm-5">
                <?php echo $this->formElement($form->get('password')); ?>
            </div>
            <?php if ($this->formElementErrors($form->get('password'))): ?>
                <div class="help-block col-xs-12 col-sm-reset inline">
                    <?php echo $this->formElementErrors($form->get('password')) ?>
                </div>
            <?php endif; ?>
        </div>

        <div class="form-group <?php echo $this->formElementErrors($form->get('newPassword')) ? 'has-error' : ''; ?>">
            <?php echo $this->formLabel($form->get('newPassword')); ?>
            <div class="col-xs-12 col-sm-5">
                <?php echo $this->formElement($form->get('newPassword')); ?>
            </div>
            <?php if ($this->formElementErrors($form->get('newPassword'))): ?>
                <div class="help-block col-xs-12 col-sm-reset inline">
                    <?php echo $this->formElementErrors($form->get('newPassword')) ?>
                </div>
            <?php endif; ?>
        </div>

        <div class="form-group <?php echo $this->formElementErrors($form->get('reNewPassword')) ? 'has-error' : ''; ?>">
            <?php echo $this->formLabel($form->get('reNewPassword')); ?>
            <div class="col-xs-12 col-sm-5">
                <?php echo $this->formElement($form->get('reNewPassword')); ?>
            </div>
            <?php if ($this->formElementErrors($form->get('reNewPassword'))): ?>
                <div class="help-block col-xs-12 col-sm-reset inline">
                    <?php echo $this->formElementErrors($form->get('reNewPassword')) ?>
                </div>
            <?php endif; ?>
        </div>

        <input type="hidden" id="estado_solicitud" name="estado" class="col-md-12 col-xs-12" value = "PENDIENTE"/>
        <div class="clearfix form-actions">
            <div class="col-md-offset-3 col-md-9">
                <button class="btn btn-info" type="submit">
                    <i class="ace-icon fa fa-check bigger-110"></i>
                    Guardar
                </button>
                &nbsp; &nbsp; &nbsp;
                <a href="" class="btn" type="reset">
                    <i class="ace-icon fa fa-undo bigger-110"></i>
                    Limpiar
                </a>
            </div>
        </div>
    </form>
</div>


<script type="text/javascript">
    jQuery(function ($) {
        $("#fecha_abono").datepicker({
            format: 'dd/mm/yyyy', // mysql
            viewMode: "days",
            language: "es"
        }).on('changeDate', function (ev) {
            $("#id_fecha_inicio").datepicker('hide');
        });

    });

</script>