<div class="page-header">
    <h1>
        Aprobar Solicitud
        <small>
            <i class="ace-icon fa fa-angle-double-right"></i>
            Solicitar Vacaciones
        </small>
    </h1>
</div>

<div class="row">
    
    <div class="col-md-12">

        <form class="form-horizontal" role="form" method="POST">

            <?php echo $this->formElement($form->get('id')); ?>
            <?php echo $this->formElement($form->get('action')); ?>

            <div class="form-group">
                <?php echo $this->formLabel($form->get('observacion')); ?>
                <div class="col-md-9">
                    <?php echo $this->formElement($form->get('observacion')); ?>
                </div>
                <?php if ($this->formElementErrors($form->get('observacion'))): ?>
                    <span class="help-inline" style="color:red;">
                        <?php echo $this->formElementErrors($form->get('observacion')) ?>
                    </span>
                <?php endif; ?>
            </div>

            <div class="clearfix form-actions">
                <div class="col-md-offset-3 col-md-9">
                    <button type="submit" class="btn btn-info">
                        <i class="ace-icon fa fa-check bigger-110"></i>
                        Guardar
                    </button>

                    &nbsp; &nbsp; &nbsp;
                    <a href="<?php echo $this->url('application/default', array('controller' => 'anticipos', 'action' => 'detalle'), array('query' => array('id' => $form->get('id')->getValue()))); ?>" class="btn" type="reset">
                        <i class="ace-icon fa fa-undo bigger-110"></i>
                        Cancelar
                    </a>
                </div>
            </div>
        </form>
    </div>

</div>